/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import UAS.util.*;
import java.awt.Color;
import java.util.ArrayList;

public class Pesan_Tiket extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Object user;
    int id_film = 0;
    ArrayList<String> films = new ArrayList<>();

    public Pesan_Tiket(Object user) {
        initComponents();
        func.config(this);
        p_side.setBackground(new Color(255, 255, 255, 245));

        this.user = user;
        tampil_jadwal("", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new UAS.util.panelGradient();
        p_side = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_close = new javax.swing.JLabel();
        btn_min = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        ttanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        twaktu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tstudio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_tiket = new javax.swing.JButton();
        btn_film = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_film = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JLabel();
        txt_genre = new javax.swing.JLabel();
        txt_durasi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        p_side.setBackground(new java.awt.Color(255, 255, 255));
        p_side.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("STFangsong", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CINEMAKU");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Film");
        jLabel5.setAlignmentX(0.5F);

        btn_tambah.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(201, 0, 0));
        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setText("x");
        btn_close.setToolTipText("Close");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        btn_min.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        btn_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_min.setText("-");
        btn_min.setToolTipText("Minimize");
        btn_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_min.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minMouseClicked(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setRequestFocusEnabled(false);
        tabel.setRowSelectionAllowed(false);
        tabel.setUpdateSelectionOnSort(false);
        tabel.setVerifyInputWhenFocusTarget(false);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        ttanggal.setPreferredSize(new java.awt.Dimension(12, 40));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tanggal");
        jLabel6.setAlignmentX(0.5F);

        twaktu.setPreferredSize(new java.awt.Dimension(12, 40));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Waktu");
        jLabel7.setAlignmentX(0.5F);

        tstudio.setPreferredSize(new java.awt.Dimension(12, 40));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Studio");
        jLabel8.setAlignmentX(0.5F);

        btn_tiket.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btn_tiket.setText("Pesan Tiket");
        btn_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiketActionPerformed(evt);
            }
        });

        btn_film.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btn_film.setText("Lihat Film");
        btn_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filmActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText(" ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cb_film.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_film.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_filmItemStateChanged(evt);
            }
        });
        cb_film.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cb_filmVetoableChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Jadwal");

        txt_judul.setBackground(new java.awt.Color(255, 255, 255));
        txt_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_judul.setText("Judul");
        txt_judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_genre.setBackground(new java.awt.Color(255, 255, 255));
        txt_genre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_genre.setText("Genre");
        txt_genre.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txt_durasi.setBackground(new java.awt.Color(255, 255, 255));
        txt_durasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_durasi.setText("Durasi");
        txt_durasi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setText("Format: yyyy-mm-dd");

        jLabel9.setText("Format: hh:mm");

        javax.swing.GroupLayout p_sideLayout = new javax.swing.GroupLayout(p_side);
        p_side.setLayout(p_sideLayout);
        p_sideLayout.setHorizontalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_sideLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_sideLayout.createSequentialGroup()
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_sideLayout.createSequentialGroup()
                                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(ttanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(twaktu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(p_sideLayout.createSequentialGroup()
                                    .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cb_film, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_sideLayout.createSequentialGroup()
                                .addComponent(btn_film, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(p_sideLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_sideLayout.setVerticalGroup(
            p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sideLayout.createSequentialGroup()
                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_min, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_sideLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_sideLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cb_film)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))))
                .addGroup(p_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_tiket)
                    .addComponent(btn_film))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filmActionPerformed
        // TODO add your handling code here:
        new Home(user).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_filmActionPerformed

    private void btn_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tiketActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_tabelMouseClicked

    private void btn_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btn_minMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String tanggal = ttanggal.getText();
        String waktu = twaktu.getText();
        String studio = tstudio.getText();

        if (tanggal.length() != 0 && waktu.length() != 0 && studio.length() != 0) {
            try {
                String sql = "INSERT INTO jadwal VALUES (null, '" + id_film + "', '" + tanggal + "', '" + waktu + ":00" + "', '" + studio + "');";
 
                Connection conn = new koneksi().getConnection();
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan!");

                tampil_jadwal("", 0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
                System.out.println("Error: \n" + e);
            }

        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void cb_filmVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cb_filmVetoableChange
        // TODO add your handling code here: 
    }//GEN-LAST:event_cb_filmVetoableChange

    private void cb_filmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_filmItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String selectedItem = cb_film.getSelectedItem().toString();

            try {
                int selectedIndex = cb_film.getSelectedIndex();
                id_film = Integer.parseInt(films.get(selectedIndex - 1)); 
            } catch (Exception e) {
            }

            // Cek jika pilihan kosong
            if (selectedItem.isEmpty()) {
                txt_judul.setText("Pilih film...");
                txt_genre.setText("");
                txt_durasi.setText("");
            } else {
                try {
                    // Ambil data genre dan durasi berdasarkan judul film
                    String query = "SELECT genre, durasi FROM film WHERE judul_film = '" + selectedItem + "'";
                    ResultSet rs = func.db.select(query);

                    // Set label jika data ditemukan
                    if (rs.next()) {
                        txt_judul.setText(selectedItem);
                        txt_genre.setText(rs.getString("genre"));
                        txt_durasi.setText(rs.getInt("durasi") + " menit");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_cb_filmItemStateChanged

    public void tampil_jadwal(String kondisi, int isCari) {
        DefaultTableModel model = new DefaultTableModel(new String[]{"No", "Judul", "Genre", "Durasi", "Studio", "Tanggal", "Waktu"}, 0);
        tabel.setModel(model);

        int tes = (Integer) tabel.size().width / 7;
        TableColumn column;
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabel.getColumnModel().getColumn(0);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(1);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(2);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(3);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(4);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(5);
        column.setPreferredWidth(tes);
        column = tabel.getColumnModel().getColumn(6);
        column.setPreferredWidth(tes);

        int notFound = 0;

        try {
            ResultSet hasil = func.db.select("SELECT j.id_jadwal, f.judul_film, f.genre, f.durasi, j.tanggal, j.waktu, j.studio, " + "f.id_film AS f_id_film, j.id_film AS j_id_film " + "FROM film AS f " + "INNER JOIN jadwal AS j ON f.id_film = j.id_film " + (kondisi != "" ? "WHERE " + kondisi : "") + " ORDER BY j.id_jadwal");  
            int i = 0;
            while (hasil.next()) {
                i++;
                String id = hasil.getString("id_jadwal");
                String fid_film = hasil.getString("f_id_film");
                String judul = hasil.getString("judul_film");
                String studio = hasil.getString("studio");
                String tanggal = hasil.getString("tanggal");
                String waktu = hasil.getString("waktu");
                String genre = hasil.getString("genre");
                String durasi = hasil.getString("durasi");

                String[] data = {Integer.toString(i), judul, genre, durasi, studio, tanggal, waktu};

                if (isCari == 1) {
                    ttanggal.setText("");
                    twaktu.setText("");
                    tstudio.setText("");

                    txt_judul.setText(judul);
                    txt_genre.setText(genre);
                    txt_durasi.setText(durasi);
                } else {
                    ttanggal.setText("");
                    twaktu.setText("");
                    tstudio.setText("");
                }

                model.addRow(data);
                notFound++;
            }

            if (notFound == 0) {
                ttanggal.setText("");
                twaktu.setText("");
                tstudio.setText("");
//                JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
            }

            // ComboBox punya
            ResultSet rs = func.db.select("SELECT id_film, judul_film FROM film");
            cb_film.removeAllItems();
            cb_film.addItem("");
            while (rs.next()) {
                cb_film.addItem(rs.getString("judul_film")); 
                films.add(rs.getString("id_film"));
            }
        } catch (Exception e) {
            System.out.println("Terjadi Error :\n" + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesan_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesan_Tiket(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JButton btn_film;
    private javax.swing.JLabel btn_min;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tiket;
    private javax.swing.JComboBox<String> cb_film;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_side;
    private UAS.util.panelGradient panelGradient1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tstudio;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JTextField twaktu;
    private javax.swing.JLabel txt_durasi;
    private javax.swing.JLabel txt_genre;
    private javax.swing.JLabel txt_judul;
    // End of variables declaration//GEN-END:variables
}
